---
- hosts: all
  gather_facts: yes
  become: True

  vars_files:
    - {ANSIBLE_VARS}

  roles:
    #- geerlingguy.firewall
    #- geerlingguy.nginx
    #- geerlingguy.php
    #- geerlingguy.adminer
    #- geerlingguy.git
    - ansible_role_git_deployer