---
# Ansible playbook for a LEMP server.
#
# @author Jeff Geerling (2014).

- hosts: all
  gather_facts: yes

  vars_files:
    - {ANSIBLE_VARS}

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.adminer
    - geerlingguy.php-mysql
    - geerlingguy.git
    - debops.postfix